### ISSUE TITLE
Blood Orb Tier 2 not craftable

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#1]
The Blood Orb Tier 2 seems not to be craftable.

I tried first using the one which was already bound to me, but then I crafted a new one thinking it might only work with unbound ones. But while the diviner puts the orb into the altar (having enough blood in it) nothing happens, the orb just stays there not crafting into the next tier.

**Comment by drz2k** [comment]
New recipe done :)
