### ISSUE TITLE
Suggestion: Magical Crop Seeds recipes

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#11]
It just came into my mind, probably you thought about this or another way yourself already, but I feel so free to write it down anyways. :)

Suggestion:
- Change the recipes of creating the magical crop seeds into a blood magic's alchemical chemistry way.
- Since the alchemical chemistry set is limited to 5 items maybe increase the costs of the seeds a bit. 
E.g. the coal seed uses "1 minicio seed, 4 accio essence and 4 coal". Could be changed to "1 minicio seed + 1 block of accio essence + 1 block of coal"
Seen on the adding of agricraft - considering magical crops get the whole agricraft ability, so stat'raising included an easier way of getting new seeds (easier seen on the normal magical crops way, where it takes a long time to get new seeds) - it wouldn't hurt too much, since most people will craft only 1 seed anyways.
Maybe even some of the blood magic's "catalysts" and "filling agents" (and such stuff) can be added for later recipes

- Progession could be limited to your blood magic tier by only allowing a certain tier of orb to be used for the recipe.

- Storywise it would fit alot I think. Something along the lines of "Infusing seeds with your own Life essence and some reagent to create new, improved seeds" (the more complex/higher tier the seed would be, the more LP it could use)

It would increase the influence of blood magic in the progression of magical crops alot.

---

Feel free to tear the idea apart :D

**Comment by drz2k** [comment]
Alchemy cant be set to a level. Thats why there is allready the magical crops transformation cirlce in the blood altar :)

Since you cant get many of the resources first to create a magical crop for it, this is the best way atm. For the magical crops with mobdrops and alike on them im planning to use witchery ;)

**Comment by Nezraddin** [comment]
Ah, I thought the alchemical chemistry set allows to specify which orb is able to be used for the recipe.
Without that of course the idea falls apart. ^^

Using the altar to craft the seeds is great, too. (my ideas tend to get always on the "the more complicated the better"-side xD )

I will close this then. Happy that I learned something new about how the tier-leveling/restrictions in blood magic works :]
