### ISSUE TITLE
Missing texture while breaking altar diviner

### ISSUE THREAD

**Issue by Pitschweiz** [Hypovolemia/hypovolemia#12]
![2015-09-13_11 55 22](https://cloud.githubusercontent.com/assets/14253878/9836139/7be32806-5a0e-11e5-9cab-a98e8014ffdd.png)

**Comment by tyler489** [comment]
Has been an issue since .3

**Comment by drz2k** [comment]
Seems it wont be fixed in the near future. Not our issue anyway :)
