### ISSUE TITLE
Sigil of the Green Grove -> Fuzzy detection

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#13]
The questbook doesn't detect the Sigil after crafting.

I kinda get the feeling, that all detection-quests loves to be fuzzy. O_o

[edit]
The Tier 2 orb quest seems to want to fuzzy, too. ^^
(Fuzzy should probably be the standard for quests, seen on how many only accept things when they're fuzzy)

**Comment by tyler489** [comment]
Confirmed issue in .6 alpha
https://gyazo.com/f3d07653a6d7061e453de43880137303

**Comment by tyler489** [comment]
the weak blood orb works in .6

**Comment by drz2k** [comment]
Cant reproduce. Even a sigi with set owner ship is detecting fine.

**Comment by Nezraddin** [comment]
That's weird, for me it's the opposite.
I re-locked the quest with the editing-questbook and tried my bound sigil, a newly crafted one and even a cheaten in one. 
All three were not detected by the questbook.

**Comment by drz2k** [comment]
Could you try it again with this hqm file?

https://github.com/Hypovolemia/hypovolemia/blob/master/quests.hqm

**Comment by Nezraddin** [comment]
Yes, with that quest-file the detection works all fine. 
At least for the Sigil, the Tier 2 Blood Orb still gets not detected.
(The questbook seems to be quiet picky what it detects and what not)

**Comment by drz2k** [comment]
I have more the feeling the repo updates are problematic. Removed the hqm and commited a fresh version of it.

**Comment by drz2k** [comment]
https://github.com/Hypovolemia/hypovolemia/issues/27

duplicate
