### ISSUE TITLE
Chest and Mousewheel bugged

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#14]
It seems in Version 0.6 the inventory tweaks (I think that's the mod) got bugged.

You cannot use the mousewheel to switch items from chest to inventory or back.
When you use the mousewheel the item "flickers" like it tries to move the same item again and again.

**Comment by Slind14** [comment]
Those are the changes that happened, I don't see what of those could have caused it.
https://github.com/Hypovolemia/hypovolemia/compare/Alpha0.4...Alpha0.6

**Comment by Slind14** [comment]
Would you mind testing if it is ender storage by temporarily removing the mod?

**Comment by Nezraddin** [comment]
Tested it:
Still bugged, so ender storage wasn't the cause for this.

Tried to delete the files and redownload the whole pack, too, in case it was a failure in updating, but that didn't help either.

Playing around with the settings you can change didn't bring any fixing, too.

**Comment by Nezraddin** [comment]
Found it:

"MouseTweaks-2.4.4-mc1.7.10" <- this mod is causing the problem.

**Comment by Slind14** [comment]
The mod has been around with 0.4 already.

**Comment by Nezraddin** [comment]
Not sure why it causes the problem now, but removing the mod fixes the mousewheel-problem.

Looking at the change-log for 0.4 again: 
I must say I'm unsure if I ever really was on 0.4. 
0.4 says it added agricraft, but for me agricraft came into the modpack only with the latest version (0.6), so I'm very unsure now if there wasn't a update-problem on 0.4 for me already, that I didn't get all the files I was supposed to have in the version.

**Comment by Slind14** [comment]
Do you prefer inventory or mouse tweaks wheel function. I guess inventory tweak's but just wanna make sure.

**Comment by Nezraddin** [comment]
From what I see about the mousewheel function of both mods, it pretty much does exactly the same.
So I think it makes no difference if the one or the other will be disabled.

Though it might be easier to disable the mousetweaks function. At least I don't see a setting in the inventory-tweaks config file for the mousewheel.

**Comment by Slind14** [comment]
https://github.com/Hypovolemia/hypovolemia/commit/6cba024fddcbbb50a8c8d88baf0827d51e5d9150
