### ISSUE TITLE
Blood Runes Quest - Possible change needed

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#15]
The questline about the blood altar runes which teaches you, how to move your blood better into the altar, starts at the moment with the tier 5 rune, while the tier 3 and tier 4 runes are later quests.

If there are no plans of making the acceleration-rune lower-tier, maybe switching the quests in tier-order would be better.

**Comment by drz2k** [comment]
absolutly correct. it goes dislocation - augmented now and then spreads to the 2 higher tier ones.
