### ISSUE TITLE
Growth Pulser Explanation -> Probably needed

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#19]
This is really just a minor thing, but for people who never used the block, it can be easilly seen as "bugged/broken", so maybe a little Hint in the questbook would be good for two things:
- It seems to not work with Agricraft (not sure if that will be changed by the modauthors in the future)
- There 'needs' to be a block of dirt between the pulser and the plant, even for oreberry-bushes. 
(I tried using it directly under the oreberry bush but that seems to not work, putting a dirt between pulser and bush made it work faster)

Really just a minor thing and people who try to figure out things will find it out in no time, but the rest might start screaming that the block is broken.

**Comment by drz2k** [comment]
Note has been added to the quest. Still need to check compatibility with agricraft.

**Comment by drz2k** [comment]
Tested with 2 magic crops, in cropsticks, on normal farmland, one with pulser, other without : 

One with pulser at 57%, the one without 14%. So i think they work ;)
