### ISSUE TITLE
Weeds disabled

### ISSUE THREAD

**Issue by tyler489** [Hypovolemia/hypovolemia#2]
If enabled, weeds can only be removed by using this Hand Rake tool [default: true]
+    B:"Enable Hand Rake"=true
+
+    # set to false if you wish to disable weeds [default: true]
+    B:"Enable weeds"=false

No need for hand rakes
Just a heads up.

**Comment by drz2k** [comment]
Well while i love the crossbredding and stuff, i feel weeds are more an annoyance.

**Comment by drz2k** [comment]
https://mineyourmind.net/forum/threads/agricraft-weeds.11963/

**Comment by drz2k** [comment]
Again : https://mineyourmind.net/forum/threads/agricraft-weeds.11963/

due to the poll ill leave weeds disabled. for now :)

**Comment by Slind14** [comment]
I think we understood him wrong. 
Due to weeds being disabled there is not need for the hand rake, which is "enabled"..
