### ISSUE TITLE
Infuser Quest after getting osmium-seeds

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#20]
Since it was mentioned in the conversation a few times and I stepped into the same trap thinking you cannot craft the infuser without steel, here for the better overlook for it :)

Maybe it would be best to put the mekanism infuser quest after the iron-sword quest where you get the osmium seeds. That would probably make more clear that people should first get the seeds before starting with mekanism. Less confusion than seeing the infuser as one of the starting-quests (unlocked with the first look in the questbook)

**Comment by drz2k** [comment]
Good idea, i will simply make it a requirement.
