### ISSUE TITLE
Suggestion: Foundry-mod taking over!

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#21]
I think it would be nice to give the foundry-mod even more controll about what you craft.
It already has the metal-tools and swords, maybe next step the armor would be nice, too. Meaning to disable all the vanilla recipes for anything that the foundry-mod can do with it's machines.

**Comment by drz2k** [comment]
Thought about that as well but pushing it a bit behind until i played with iguana tweaks and decided about ticon stuff :)

**Comment by drz2k** [comment]
https://github.com/Hypovolemia/hypovolemia/commit/e326db4339dc5635c8a59ca91e4d730b2b032012

https://github.com/Hypovolemia/hypovolemia/commit/a53016942cafb64735be3381a1197a4787c1acaa
