### ISSUE TITLE
Feedback (not formatted as an issue, sorry!)

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#22]
**Bugs (not all are fixable in the modpack unfortunately):**
Growing plants faster-manual quest does not detect the item.

Default lore button "L" is blocked by dynamic lights toggle.

Mouse wheel scrolling to move items between inventories doesn't work properly.

Right click events aren't being halted when harvesting oreberry bushes or agricraft plants. This causes you to place blocks and torches accidentally.

**Suggestions:**
Iguana Tinker Tweaks would be a nice addition to the pack for it's part swapping ability on tools.  Tool leveling could be disabled if that is a concern, although for the most part I don't see this pack as being effected by it much since there is very little physical harvesting of anything involved in it.

The only viable food source that I can find seems to be apples for quite a long time, and even these are hard to produce in any quantity without a fairly large tree farm.  Some alternate food production methods early on would be nice, as sapling production tends to be rather slow. (Fast leaf decay might be the answer to speed up sapling gathering.)

As of right now, both carrot and potato seeds aren't creatable by mutation with agricraft, locking away most of the mutation tiers for alternate food production as you can't aquire these two foods in the world. (intended?)

Concerning blood magic,  there are a few things that I noticed could be added/changed/rearranged:
1. Introduce/Describe the blood network for anyone who is new to blood magic. For lore this could go either on the blood magic lore page, or a new lore page triggered before it is mentioned in "Growing plants faster-manual"  Best yet, this lore could be given to you when you complete the blood orb quest (see number 2).
2. Speaking of the quest "Growing plants faster-manual", you can't really use the blood network, or this sigil, without first making a weak blood orb and putting blood into your network. With that in mind, shouldn't a blood orb be crafted before this quest?
3. Introduce/Describe a divination sigil sooner. This might require a recipe change to make it earlier or rearrange the quests like I mentioned in 2, and put the divination sigil quest next to the growing ones, all below the blood orb quest.  I just think it's important for players to be able to see their altar/blood network levels LONG before you make a tier 2 altar (which is where it looks like you have it).  So much of the beginning uses blood magic to convert items that you end up blindly guessing if there is enough blood in the altar or if you are capped.

**Spelling fixes**
Lore book:
Welcome to hypovolemia lore page: 
"When you got an item" = "When you get an item"
"immediatly" = "immediately"
"followup" = "follow-up"
Bloodmagic:
"allways" = "always"
"avaible" = "available"

Quest book:
Intro text "If feels wrong." Should be "It feels wrong."
Tier 1:
Maybe if I regret my sins
	"Whatever god feels to hear my regrets" = sounds odd.  Perhaps:
	"Whatever god decides to hear my regrets"
They must be joking!
	"usefull" = "useful"
Wait plants?
	"amusment" = "amusement"
Self confidence
	"I start to think that I do not rely on the gods" = sounds better as:
	"I start to think that I should not rely on the gods"
Tier 2:
Improving the Altar
	"powerfull" = "powerful"

That's all I have so far.  I'll keep looking though.

**Comment by Slind14** [comment]
:+1:

**Comment by Slind14** [comment]
It is a little hard to keep track of the different issues/suggestions. Would you mind creating one issue per topic? This way it is easier to comment on and they can be closed out once solved.

**Comment by Delerium** [comment]
Sure, I'll separate it out.
