### ISSUE TITLE
[Bug] [minor] bound to caithleen Owner Nbt Bug Quest reward

### ISSUE THREAD

**Issue by tyler489** [Hypovolemia/hypovolemia#25]
![2015-09-15_19 53 25](https://cloud.githubusercontent.com/assets/7015040/9893931/b3da064a-5be3-11e5-8a0c-f0bfa64fc138.png)
Sorry i cant use that ;)

**Comment by tyler489** [comment]
recieved from sockets of blood quest tier 2

**Comment by Bennyboy1695** [comment]
Please use a more appropriate title when creating issues as it makes it easier to find again when its closed

**Comment by tyler489** [comment]
Better benny?

**Comment by Bennyboy1695** [comment]
Much better thanks :) Also an easy mistake to make, caith probably didnt realize the one set as reward was already bound

**Comment by tyler489** [comment]
yeah  caith probably dont want everone using her blood on the server though:) when there is a server
