### ISSUE TITLE
Possible quest reorder

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#26]
Concerning blood magic, there are a few things that I noticed could be added/changed/rearranged:
1. Introduce/Describe the blood network for anyone who is new to blood magic. For lore this could go either on the blood magic lore page, or a new lore page triggered before it is mentioned in "Growing plants faster-manual" Best yet, this lore could be given to you when you complete the blood orb quest (see number 2).
2. Speaking of the quest "Growing plants faster-manual", you can't really use the blood network, or this sigil, without first making a weak blood orb and putting blood into your network. With that in mind, shouldn't a blood orb be crafted before this quest?
3. Introduce/Describe a divination sigil sooner. This might require a recipe change to make it earlier or rearrange the quests like I mentioned in 2, and put the divination sigil quest next to the growing ones, all below the blood orb quest. I just think it's important for players to be able to see their altar/blood network levels LONG before you make a tier 2 altar (which is where it looks like you have it). So much of the beginning uses blood magic to convert items that you end up blindly guessing if there is enough blood in the altar or if you are capped.

**Comment by drz2k** [comment]
#3 - lore page has been added and will be given out at sigil quest completion. I think the order is fine - i think some "this stupid thing does nothing .... oh a note" is a nice twist :)

**Comment by drz2k** [comment]
Oh that also handled #1 ;)

**Comment by drz2k** [comment]
#2 the quest is now avaible from the start
