### ISSUE TITLE
Quests that do not detect/complete.

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#27]
1st page: "Growing plants faster-manual" = Sigil of the green grove doesn't detect
2nd page: "Insight" = sigil of sight doesn't detect (two sigil problems. possibly due to "owner" setting?)
3rd page: "Starting to grow things!" = this whole quest grouping works fine with default seeds, but does not detect analyzed seeds.

**Comment by drz2k** [comment]
to be reviewed

**Comment by drz2k** [comment]
Seems the fixes worked since no one reported this again - closing.
