### ISSUE TITLE
Rune quests seem out of order.

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#30]
The "Pumping Blood `#2`" quest is unlocked right next to "Improving the altar" where you first make a tier 2 altar, but it requires you to make a rune of dislocation, which requires a tier 3 altar at a bare minimum.  It feels like it's in a strange place considering that it unlocks next to, and at the same time as, making a T2 apprentice blood orb.

This quest seems better in-line with the augmented capacity rune quest above in the "tier 3" section of the quest book.  Speed, sacrifice, and self-sacrifice runes are the only runes you can make at this level (tier 2) besides the basic blood rune, and would be better placed down in that area.

**Comment by drz2k** [comment]
Thats intended. The questline explains how to effectivly pump blood into the altar and is a progression in itself. Better altars-advance this line, make better blood pumping.
