### ISSUE TITLE
Quests that do not complete part 3

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#32]
Page 4: "Without the gods"
"storing energy"
Possibly alot more on this page don't detect completion.

**Comment by drz2k** [comment]
To review - other machines in the questline.

**Comment by Nezraddin** [comment]
Hijacking this issue, since it fits into the title:

In the Blood magic questline the Ritual Diviner doesn't get detected.
(not sure if that should be a new issue, the title fitted so I put it in here)

**Comment by Delerium** [comment]
Tested the newest github on this issue, and I think the detection changes became too broad on mekanism.  Most of the machines have the block id of 1072, with all basic factories being 1072:5.  As a result, all of these quests auto-complete when any machine with a block id of 1072 is made: Without the gods, Triple It, Crush of clumps, Factories, Advanced factory, Elite factory.  With "No end in sight", any block with an id of 1073 will trigger it, like an electrolytic seperator or portable tanks.

Also, the "triple it" quest seems to be looking for a basic purifying factory, but I think you may have meant for it to be a purification chamber since you mention that in the text.

**Comment by drz2k** [comment]
Changed it to the chamber - good finding. Chenged the other machines to non fuzzy but NBT independet. This seems to do the trick in my testing. Still need review of the other machines :)

**Comment by Delerium** [comment]
Sorry, I've been busy with work this past week.  I'll try and test the rest of the machines tonight.

**Comment by drz2k** [comment]
No worries, im struggling with a flu too, so theres not so much progress atm :)

**Comment by Slind14** [comment]
any news?

**Comment by drz2k** [comment]
Closing this and waiting for new reports on these issues.

**Comment by shadowpanther** [comment]
"No end in sight" autocompleted for me. I haven't made Chemical Injection Chamber.
