### ISSUE TITLE
Wooden Planks/Wooden Splinters-Quests mixed up(?)

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#33]
It seems, that the two quests for "Wooden Splinters" and "Wooden Planks" are in the wrong sequence.

At the moment first it asks for the planks before the splinters, even though you make the planks out of the splinters.

**Comment by drz2k** [comment]
Humm it _might_ seem misleading. The intention is to have the player make planks from bones. Since this is tedious and bones are somewhat limited the more bone pillars you removed theres the other way with trees->planks. So its kinda the advanced generation method.

**Comment by Nezraddin** [comment]
I see, then it really just mislead me, since I wasn't thinking about the bone -> woodplank recipe anymore. 
In this case it does make sense, yep. I'll close this then again. Was my mistake, sorry :)

**Comment by drz2k** [comment]
no worries :)
