### ISSUE TITLE
Quest: Veins

### ISSUE THREAD

**Issue by Pitschweiz** [Hypovolemia/hypovolemia#35]
The quest Veins in the first chapter asks for 10 basic mechanical pipes.
After crafting you get 8 pieces but it recognizes only the crafting. So to complete this quest you need to craft 80 basic mechanical pipes.

**Comment by Delerium** [comment]
The version I'm playing (0.8) completed after two crafts, 8/10 then 10/10 respectively.  Wonder why...

**Comment by Slind14** [comment]
How did you both craft them? (which crafting table..)

**Comment by Delerium** [comment]
I just did some testing on it with the regular and ticon crafting stations, and both performed the same: If you shift-click the result into your inventory, you only get credit for 1/10, but if you manually click the result and place it in your inventory, you get credit for 8/10.  It's an odd bug.

**Comment by Slind14** [comment]
Would changing the detection to "possession" break progression? Or changing it to 1 or 2. I doubt that we will be able to solve the real issue.

**Comment by Delerium** [comment]
Possession would be fine. There was no reward for completing it, and I didn't see any given in quest rewards, so ultimately it would just be "make sure you have these because you will need them."

**Comment by drz2k** [comment]
Changed to detection and giving out some juicy apples :)
