### ISSUE TITLE
Suggestion: endgame fabrication via blood import

### ISSUE THREAD

**Issue by AlphaRue** [Hypovolemia/hypovolemia#36]

**Comment by drz2k** [comment]
Suggestion: Describe the idea :dancer: 
This one ?
alpharue 11:29 PM recipe suggesting for manasteel gear replace 1 iron igot with 1 neutronized metal

**Comment by AlphaRue** [comment]
that was a seperate suggestion, this was the one with project E and pumping blood

**Comment by drz2k** [comment]
Which gives me still no clue on what this is about.

**Comment by Delerium** [comment]
If I'm inferring correctly, I think he wants project E in the pack, and to be able to pump blood into the transmutation table to convert into EE, and fabricate items from that.  To me that seems like an odd/complicated direction to head with the pack.

**Comment by AlphaRue** [comment]
pretty much what delerium said, with the condition that items cant be converted to EE

**Comment by Delerium** [comment]
you would probably need to write a mod to get that level of interaction between project E and blood.  I'm thinking it might be beyond the scope of what a modpack can do.

**Comment by drz2k** [comment]
ProjectE allready disqualifies at license. We are not allowed to mirror it, so no ftb/curse and i dont think slind wants to introduce that annoying "we will now open a browser, download the mod" thing into mym launcher.
