### ISSUE TITLE
Armor crafting recipes

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#37]
Right now from what I can tell iron armor is stuck behind a crafting loop from foundry.  All of the armor mold recipes require iron or above quality pieces to craft the molds, but you can't actually craft any of the armor pieces to use to make the molds with.  The "Better tools" quest rewards you with a helmet mold, but you have no way of making any of the others.  My suggestion would be to add mold recipes using wooden armor pieces, thus allowing us to make iron armor.  (also diamond armor recipes seem to be disabled? intentional?)

**Comment by drz2k** [comment]
diamond is intentional.

i hoped the molds could be created from wood right away, but seems ill have to make recipes for them.

**Comment by drz2k** [comment]
https://github.com/Hypovolemia/hypovolemia/commit/82b05ee7a5cf48e872d8159c261b97fc1aaafb9a
