### ISSUE TITLE
Refactory Hopper deletes contents when mined.

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#38]
Just a warning I guess since it's a foundry issue I'm assuming, but if you mine (to pick up) a refactory hopper, it will delete everything inside it, including any tanks you had inside draining.  It doesn't drop it's item contents like chests do, nor does it preserve it's fluid contents (although that may be intended).

**Comment by drz2k** [comment]
Issue has been closed by moddev appointing a fix.
