### ISSUE TITLE
Reward-issue in a quest (minor)

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#39]
In the Blood Magic Questline:
- The quest for crafting the Ritual Diviner gives you an "Elemental Inscription Tool: Fire" as a reward. But once you have the ritual diviner you never will need the inscription tool ever again.

Maybe change it to one of the dusk-tools, so the one you need a coalblock and tier 4 altar for. Which you need later for upgrading the ritual diviner.

**Comment by drz2k** [comment]
Humm i thought the tools loose durability even when using a diviner

**Comment by Nezraddin** [comment]
From what I know, the tools only loose durability when you're using them directly. The ritual diviner itself has infinite durability (unless there is a setting in the configs to activate durability for it).

**Comment by drz2k** [comment]
Well then the rewards is pretty crappy and i will change it :)

**Comment by drz2k** [comment]
The quest before has been reduced by 4 ritual stones which are now given out in the divner quest.
