### ISSUE TITLE
Vanilla crop seeds that need recipes

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#40]
Both carrot and potato seeds aren't creatable by mutation with agricraft.  This also has the effect of making it impossible to mutate into sugar cane seeds, the only source of sugar and paper for books.  

There is a recipe to turn a hay bale into one sugar cane, but this involves botania which I thought we weren't supposed to touch yet.  Also in botania is a method to convert wheat -> potato -> carrot, but this requires an alchemy catalyst.

If you don't want to use crop mutation (I don't see it used anywhere else) then my suggestion would be to do a conversion circle in the blood altar just like the element seeds on the "Fertilisation" page, with the order mimicking botania's cycle of seed->potato seed->carrot seed->*sugar cane seed* (inserted by me)->back to seed (optional addition of melon seed->pumpkin seed->cocoa beans).  This could even be put as a circle set of quests right after "Irrigation".

**Comment by Nezraddin** [comment]
From what I read, you get these seeds from bonemealing grassblocks. 
Grassblocks can be created with blood magic (in die alchemical thing).and to get enough bonemeal for drops shouldn't be a problem :)

**Comment by Delerium** [comment]
Perhaps, but the recipe for grass blocks requires a blood shard to make, which is pretty far along in the progression (need ritual making to get a bound sword) to be gating basic seeds behind.

**Comment by drz2k** [comment]
The blood shards are for automation purposes. Botania has a quite cheap solution to this i think ;)

**Comment by Delerium** [comment]
That's cool. Since I'm testing here, I'm trying to follow the direction of the modpack and I didn't know if I was allowed to use the botania methods to get potato/carrot/sugar canes.

**Comment by drz2k** [comment]
In current state its a bit bad - but it will solve itself with botania and getting grass - bonemealing it. Thoo i will look into that crossbreeding now.

**Comment by drz2k** [comment]
Mutations itself work, thoo im so evil i just disabled bonemealing the cross-cropsticks for it.

So its either getting a potato/carrot seed from mobs/chests or later with botania :)
