### ISSUE TITLE
Smeltery -> disabled recipes

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#42]
I saw that the normal smeltery-controller is disabled as recipe. I know this is to put the foundry mod into the foreground (which I like, the mod is nice :) ).

I think it would be best then, to disable all recipes to the smeltery (besides the casting table, since you need this one for making parts, unless it can be made work in the foundry caster-machine) so people don't fall into the trap of making a whole bunch of seared bricks just to see in the end that they cannot make the controller.

Besides that I think, if the smeltery is to be disabled, the second recipe should be disabled too. The one you make with these other kind of seared bricks, which are crafted with nether-stuff.

**Comment by drz2k** [comment]
Well i cant disable seared bricks since foundry does only have a few molds, so i need the casting table in it if we want more tinkers tools. Probably just disabling the bricks too and putting in another lorepage.

**Comment by Nezraddin** [comment]
Ah sorry, I think I didn't made clear what I meant:

What I wanted to say is not disabling the whole seared bricks, but the "Smeltery controller", "Smeltery Tank", "Smeltery Drain" . So everything related to building the smeltery itself (the multiblock).

At the moment, with only the controller disabled, people might craft everything (tank, drain, lots of blocks) and notice too late that the controller is disabled to craft.

So the caster table and the seared blocks should of course stay enabled. (for making the molds and the blocks for making the toolforge, and it can still be a decorative block to build with).

**Comment by AlphaRue** [comment]
but that would make it so I cant build cheaty uber earlygame blood transport :(

**Comment by drz2k** [comment]
Casting table and grout are gone. Everything should be done with alchemy and the foundry.

I allready added the usual tools like axe, pick and their bigger variants. Weapons will not come in.

Do we need the chisel from ticon for anything?

**Comment by drz2k** [comment]
https://github.com/Hypovolemia/hypovolemia/issues/41

**Comment by Nezraddin** [comment]
With Chisel 2 in the pack, I don't think we would need the chisel of ticon. 
Though I never used it before, always used chisel 2, so maybe there is someone who thinks different from me. ^^

**Comment by frogman79** [comment]
Never used tcon chisel myself not with chisel 2 in a pack anyway.

**Comment by drz2k** [comment]
Allright, thx guys. No ticon chisel then! :D
