### ISSUE TITLE
Suggestion: Mobspawner as Questreward

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#43]
Concerning, that you need some sort of "steady" blood-generation at some point (I don think pumping dry blood lakes is really a long-time plan) you need some sort of steady mobspawning, and the vanilla-mechanic for that is very unreliable to really power your sacrifice-altar for it.

I know you can move spawners with these teleposers from Bloodmagic, but the problem here is: Finding an existing spawner in the world. This can proof quiet difficult and a long-time search. 

So I was wondering if maybe it wouldn't be bad to get 1 free spawner through a quest-reward. Maybe in the later stages of the blood magic questlne (to not make it 'too' easy in the early stages of the game, maybe behind the tier 5 quest, so as reward for fighting your first 4 withers).

Of course it can be seen as a challange to find a mobspawner in the world to improve your altar-setup, but I think we all know the feeling: Once you actually 'need' one of these spawners you spend days finding none. ^^

**Comment by frogman79** [comment]
Nether, blaze spawner(s) and actually if you dig down to level 10 ish and have a bucket nether portals are fairly early game, lots of lava around. Also ready made ish cobble gens.

**Comment by Nezraddin** [comment]
AH oh well.... I totally always forget about the nether-spawners :(
Thanks for reminding me about them! I just tried for like 7~8 hours in the past few days to find a spawner in the overworld, before I posted this one here ^^"

Still... I stay with the idea, specially seen on servers where even nether-spawners gets taken or destroyed quiet fast.

**Comment by frogman79** [comment]
No I totally agree that that it would be nice, it would save on spawners in a server environment. Nether is full of blood so moving an altar over there would be worth it either way, if you could keep it chunk loaded. I can see a Sirwill endertank with lava in it this time around as fast as I'm pumping up blood and shoving it into my altar.

Don't forget about the redstone block/1.7 thing though. Cheaty but its single player I won't judge.

**Comment by drz2k** [comment]
Well blood support is seriously given. Setup a pump at an ocean or in the nether and fill some of those huge sanguimancy tanks. (Or even setup a crossdimensional tank, we got enderstorage). You will never top this generation with vanilla blood magic. On the spawners, i think there might be a very expensive way to get them. Since nether forts, its no issue for singleplayer and servers should reset their nether every so often. Maybe some wichtery boss will drop something that can be turned into a spawner later.

**Comment by Nezraddin** [comment]
Ah, the Nether has bloodlakes, too?

Guess my spawn was too high up. I only saw very little lava (from some of the ceiling-lava-pockets) and else only darkness in the deep, so I thought the lava was just deleted (down to bedrock) or even worse, there was void on the deep.
My bad for not noticing, that there is blood to be pumped in the nether, too. ^^"

Should I close it, or let it open for a "maybe will be added, maybe not"?

**Comment by drz2k** [comment]
let it open until i made my mind up on spawnerns ;)

**Comment by drz2k** [comment]
Endgame recipe for making spawners has been added.
