### ISSUE TITLE
Apparent force-kick due to mod interactions (?) on the server

### ISSUE THREAD

**Issue by chuggafan** [Hypovolemia/hypovolemia#47]
Basically all i know is that when at least (I) join the server kicks me, if there is going to be a stable server i do really hope this does get fixed (I have no clue what is causing this, and the server logs are basically the only thing that can help) thanks

**Comment by drz2k** [comment]
asking for a stable server for somethin in alpha. Really?

**Comment by drz2k** [comment]
providing no usuable info ofc makes you the perfect tester.

**Comment by drz2k** [comment]
i think we should end your alpha test :)

**Comment by chuggafan** [comment]
I cannot provide any info because I'm getting kicked with no log for the kick.... and no, i don't expect a perfect server, which is why i'm reporting this in hopes of an investigation so that a fix can be deployed... when you get kicked with a "A fatal error has occured, this connection is terminated" you don't get no log on your end...
