### ISSUE TITLE
Possible Recipes

### ISSUE THREAD

**Issue by MaelstromPhx** [Hypovolemia/hypovolemia#48]
First off, please make crop sticks give 4. It's such a pain to make all the splinters and infuse, etc. 1 log is equivalent to 2 crop sticks, which is 1 plant. It gets extremely tedious :P

Anyway, here were some of my ideas for additional recipes:
Botania Mystical Flowers: 16 minecraft dyes and 1 flower for each dye. Just make the dye infuse into the flower in the blood altar. 

Oreberry Bushes: Possibly by infusing the respective berry or magical crops essence in an altar to make another bush. Would be nice to have but not really needed.

**Comment by drz2k** [comment]
On cropsticks - no problem if you automate your altar which is possible quite early on.

Botania Flowers are allready avaible with the fertilizer. Do we need a second way?

Oreberry bushes would probably become too powerfull if you could replicate them. I would have to make it tier4+ and at that time you allready dont need them anymore. We could talk about giving out more thoo when need arises.

**Comment by chuggafan** [comment]
Since this goes along with the suggestion, i want to suggest the ability to make a diamond sword so you can make a bound blade for 2 players if you're in a party

**Comment by drz2k** [comment]
https://github.com/Hypovolemia/hypovolemia/commit/91e2ef87f062765edd900f0ca724a46320eb2e34

**Comment by drz2k** [comment]
Ill make recipes for the other tools. Probably involving a shard.

**Comment by drz2k** [comment]
It has been hotfixed on the server for now. You can make the diamond stuff thoo nei doesnt show it.
