### ISSUE TITLE
Magical Crops Seeds disappearing

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#5]
A little weird bug, cannot really tell what is happening:

After crafting the fire-seeds and now after the coal-seeds, the seeds suddenly just disappared from my inventory.
I crafted them normally, was able to put them into my inventory, but after closing the inventory, getting dirt and hoe to plant them, they're suddenly gone.

Cheating in the seeds seem to work normally, they don't disappear. But the fire and coal seeds I crafted normally just vanished without trace.

**Comment by Slind14** [comment]
Are you able to reproduce it? If so could you give detailed steps?

**Comment by Nezraddin** [comment]
After a little testing I found the issue:
When you right-click a chest (to open it) with a magical crop seed in your hand, the seed is deleted.

Seems to happen every single time you do that. (tested with coal-seeds)

**Comment by Slind14** [comment]
:+1:

**Comment by Slind14** [comment]
verified
