### ISSUE TITLE
Problems with pushing Blood into the Blood Altar

### ISSUE THREAD

**Issue by Nezraddin** [Hypovolemia/hypovolemia#6]
I tried using the setup which was shown on a picture to the modpack, the mechanical pipes directly attached to the blood altar, but it seem they cannot push the blood into it directly.

After that I used the refractory hopper of foundry as a buffer. At the beginning it worked, but for some reason it suddenly stopped working after 1020 LP were in the altar. Couldn't figure out why it stopped (had no redstone signal or so beside it)
The end-setup with a mekanism tank on top of the refractory hopper which pushes the blood into the altar worked fine in the end.

I'm not sure if that is considered a real issue here (besides the weird behaviour of the hopper suddenly stopping to work for no reason) or a crossmod-problem that can only be fixed by the mod-authors. But I thought I better mention it. :)

**Comment by drz2k** [comment]
Mechanical pipes can be set to push on the altar, thoo its not needed.

Blood altars have internal tanks. Check those with the sigil of sight. Its also totally normal for the altar to first flood those tanks (thats why you see blood decreasing on a new placed altar, it fills the output tank). The speed the altar can pull/push to the internal tanks is heavily dependant on the setup. Theres an explanatory line in the second questline.

**Comment by Nezraddin** [comment]
You're right. 
I forgot about the internal tank and got tricked from it :(
And after some testing done, I noticed that - unlike the normal hopper or the liquid hopper from pneumaticcraft - the foundry-hopper only accepts input from the top, not from the side (even with "Push"-setting of the mechanical pipes).

So it was just a mistake on my side. Sorry ^^"
