### ISSUE TITLE
'While my energy lowers' not completing

### ISSUE THREAD

**Issue by TheIcyOne** [Hypovolemia/hypovolemia#9]
In the first questline, the quest to craft a blood dynamo will not complete. The dynamo was crafted with 8 redstone blocks and a blood altar in a crafting station.

**Comment by TheIcyOne** [comment]
This issue also applies to 'Self confidence', which requires the crafting of a metallurgic infuser.

**Comment by drz2k** [comment]
Changed infuser to nbt independent detection. blood dynamo to detection task.
